### PR TITLE
Updates run_lora_clm.py with enhanced dataset support

### PR DESCRIPTION
**Pull request by dmsuehir**
This is a PR on my fork for peer review before submitted to the upstream repo. This script previously supported two datasets from Hugging Face hub for non-SQL prompt situations: `tatsu-lab/alpaca`and `timdettmers/openassistant-guanaco`. The `timdettmers/openassistant-guanaco` dataset only has one column named `text`, whereas the `tatsu-lab/alpaca` has the standard `instruction`, `input`, and `output` columns.

To support more datasets, I added arguments to allow the user to specify column names for "instruction", "input", and "output" (or in the case of using SQL prompts it's "question", "context", and "answer"). If the user provides custom column names, I am renaming those columns to use the standard names (instruction/input/output or question/context/answer) so that the rest of the code in the script will work as expected. Also, for non-SQL prompt datasets, the "input" is optional (which is why there's a "prompt_with_input" and "prompt_without_input" template), but the existing code was handling the situation where the "input" column was blank. I updated the code to also handle the "input" column not existing at all.

I left the code specific to `timdettmers/openassistant-guanaco` alone, since that was a more special use case where there is only one column with already formed prompts. If there was interest in generically handling more datasets like this one, I could look into that in a follow up PR. 

I tested this update with several different datasets: databricks/databricks-dolly-15k, ruggsea/stanford-encyclopedia-of-philosophy_instruct, b-mc2/sql-create-context, flytech/python-codes-25k, gbharti/finance-alpaca, medalpaca/medical_meadow_medical_flashcards

As an example, [`databricks/databricks-dolly-15k`](https://huggingface.co/datasets/databricks/databricks-dolly-15k) is a dataset that has different column names than the code expects. To use `run_lora_clm.py` with this dataset, you can include args for `--input_column_name "context"` and `--output_column_name "response"`.
```
  python run_lora_clm.py \
  --model_name_or_path huggyllama/llama-7b \
  --dataset_name databricks/databricks-dolly-15k \
  --dataset_concatenation True \
  --per_device_train_batch_size 16 \
  --evaluation_strategy "no" \
  --save_strategy "no" \
  --learning_rate 1e-4 \
  --warmup_ratio  0.03 \
  --lr_scheduler_type "constant" \
  --max_grad_norm  0.3 \
  --gradient_accumulation_steps 1 \
  --learning_rate 2e-4 \
  --num_train_epochs 3 \
  --output_dir /tmp/output \
  --overwrite_output_dir \
  --validation_split_percentage 20 \
  --use_fast_tokenizer False \
  --lora_rank 8 \
  --lora_alpha 16 \
  --lora_dropout 0.1 \
  --lora_target_modules q_proj v_proj \
  --do_train True \
  --do_eval True \
  --use_habana \
  --use_lazy_mode \
  --adam_epsilon 1e-08 \
  --lr_scheduler_type "constant" \
  --max_grad_norm  0.3 \
  --bf16 \
  --throughput_warmup_steps 3 \
  --input_column_name "context" \
  --output_column_name "response" \
  --max_steps 50 \
  --max_eval_samples 50
```
This can also be run without the `--input_column_name` arg, which would then test the use case where a dataset does not have an "input" column at all.

### CODE REVIEW

**Review by okhleif-10 — COMMENTED** [review]
LGTM

**Review by ashahba — APPROVED** [review]
LGTM!

**Comment by ashahba** [comment]
On your PR description:
`--output_dir /tmp/output\` -> `--output_dir /tmp/output \`

**Comment by dmsuehir** [comment]
> On your PR description: `--output_dir /tmp/output\` -> `--output_dir /tmp/output \`

Fixed, thanks

**Comment by dmsuehir** [comment]
PR was made and merged to the upstream repo

**Pull request closed without merging**
